package com.br.crud.ticket.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.UUID;
import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name = "ticket")
public class TicketEntityV2 {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String openedBy;

    @DynamoDBAttribute
    private String closedBy;

    @DynamoDBAttribute
    private Long openedAt;

    @DynamoDBAttribute
    private Long closedAt;

    @PrePersist
    private void prePersist() {
        if (id == null) {
            id = UUID.randomUUID().toString();
        }
        if (openedAt == null){
            Date date = new Date();
            openedAt = date.getTime();
        }
    }
}
